version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD:-passwd}
      PGUSER: ${POSTGRES_USER:-postgres}
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT:-15432}:5432

  app:
    build: .
    # restart: always
    command: sh ./start_server.sh
    environment:
      APP_ENV: production
    depends_on:
      - db
    ports:
      - 127.0.0.1:${LOCAL_WEB_PORT:-8000}:8000

  chrome:
    image: seleniarm/standalone-chromium
    # image: seleniarm/standalone-firefox
    shm_size: 2gb
    ports:
      - 127.0.0.1:${SELENIUM_PORT:-4444}:4444
      # - 127.0.0.1:5900:5900  # Video Stream
      # http://localhost:7900/?autoconnect=1&resize=scale&password=secret
      - 127.0.0.1:${SELENIUM_VNC_PORT:-7900}:7900 # VNC server
    environment:
      HUB_QUIET_TIMEOUT: 180000
      HUB_TIMEOUT: 180000
      HUB_POLLING_TIMEOUT: 180000
      SE_NODE_SESSION_TIMEOUT: 180000
      ENABLE_AUTOMATION: 1

volumes:
  db_data:
