version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD:-passwd}
      PGUSER: ${POSTGRES_USER:-postgres}
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT:-15432}:5432

  app:
    build: .
    # restart: always
    command: sh ./start_server.sh
    environment:
      APP_ENV: production
    depends_on:
      - db
    ports:
      - 127.0.0.1:${LOCAL_WEB_PORT:-8000}:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      # - "traefik.http.routers.portainer.tls=true"
      # - "traefik.http.routers.portainer.tls.certresolver=myresolver"

  chrome:
    image: seleniarm/standalone-chromium
    # image: seleniarm/standalone-firefox
    shm_size: 2gb
    ports:
      - 127.0.0.1:${SELENIUM_PORT:-4444}:4444
      # - 127.0.0.1:5900:5900  # Video Stream
      # http://localhost:7900/?autoconnect=1&resize=scale&password=pass
      - 127.0.0.1:${SELENIUM_VNC_PORT:-7900}:7900 # VNC server
    environment:
      HUB_QUIET_TIMEOUT: 180000
      HUB_TIMEOUT: 180000
      HUB_POLLING_TIMEOUT: 180000
      SE_NODE_SESSION_TIMEOUT: 180000
      ENABLE_AUTOMATION: 1
      SE_VNC_PASSWORD: ${SELENIUM_VNC_PASSWORD:-pass}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chrome.rule=Host(`browser.localhost`)"
      # - "traefik.http.routers.portainer.tls=true"
      # - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - "traefik.http.services.chrome.loadbalancer.server.port=7900"


  traefik:
    image: traefik
    restart: always
    ports:
        - 127.0.0.1:8080:80
        # - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Certificates
      # - "./data/traefik/:/data"
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
    depends_on:
      - app
      - chrome

  redis:
    image: redis
    ports:
      - 127.0.0.1:${REDIS_LOCAL_PORT:-6379}:6379

  worker:
    build: .
    # restart: always
    command: sh ./start_worker.sh;
    environment:
      APP_ENV: production
      REDIS_URL: redis://redis/
    depends_on:
      - db
      - redis
      - chrome
volumes:
  db_data:
