"""bot_refactor

Revision ID: 035e32344534
Revises: dbfa54df8f21
Create Date: 2023-08-08 15:35:16.516504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "035e32344534"
down_revision = "dbfa54df8f21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets_date", schema=None) as batch_op:
        batch_op.alter_column(
            "date",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.Date(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets_date", schema=None) as batch_op:
        batch_op.alter_column(
            "date",
            existing_type=sa.Date(),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
