"""tg_chat

Revision ID: 4163664b309f
Revises: a45e1ba4e8df
Create Date: 2023-08-22 16:27:16.596409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4163664b309f'
down_revision = 'a45e1ba4e8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    with op.batch_alter_table('telegram_chats', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_telegram_chats_chat_id'), ['chat_id'])
        batch_op.drop_constraint('fk_telegram_chats_chat_id_bot', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_chats', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_telegram_chats_chat_id_bot', 'bot', ['chat_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_telegram_chats_chat_id'), type_='unique')

    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    # ### end Alembic commands ###
