"""user remove activated

Revision ID: 623673a2c254
Revises: 8af358c0fb48
Create Date: 2023-08-09 18:17:34.247218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "623673a2c254"
down_revision = "8af358c0fb48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets_date", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("activated")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("activated", sa.BOOLEAN(), autoincrement=False, nullable=True)
        )

    with op.batch_alter_table("tickets_date", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    # ### end Alembic commands ###
