"""celery

Revision ID: 6c4533c578eb
Revises: 6a7135cb0174
Create Date: 2023-08-08 18:08:04.003276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6c4533c578eb"
down_revision = "6a7135cb0174"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DOWN",
                "START",
                "UP",
                "STOP",
                "WARNING",
                "ERROR",
                "CRITICAL",
                "CLEAN",
                name="botstatus",
            ),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("message", sa.String(length=256), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot")),
    )
    op.create_table(
        "tickets_date",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("total_tickets", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets_date")),
    )
    op.create_table(
        "bot_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL", name="botloglevel"
            ),
            nullable=False,
        ),
        sa.Column("message", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bot.id"], name=op.f("fk_bot_logs_bot_id_bot")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_logs")),
    )
    op.create_table(
        "tickets_time",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_date_id", sa.Integer(), nullable=False),
        sa.Column("clock", sa.Time(), nullable=False),
        sa.Column(
            "floor",
            sa.Enum("FIRST", "SECOND", name="floor"),
            server_default="FIRST",
            nullable=False,
        ),
        sa.Column("tickets", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_date_id"],
            ["tickets_date.id"],
            name=op.f("fk_tickets_time_ticket_date_id_tickets_date"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets_time")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tickets_time")
    op.drop_table("bot_logs")
    op.drop_table("tickets_date")
    op.drop_table("bot")
    # ### end Alembic commands ###
