"""task_id

Revision ID: 8af358c0fb48
Revises: 035e32344534
Create Date: 2023-08-08 17:24:19.699025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8af358c0fb48"
down_revision = "035e32344534"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bot", schema=None) as batch_op:
        batch_op.alter_column(
            "task_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=64),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bot", schema=None) as batch_op:
        batch_op.alter_column(
            "task_id",
            existing_type=sa.String(length=64),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
