"""bot

Revision ID: dbfa54df8f21
Revises: df2e5a79269f
Create Date: 2023-08-07 17:38:56.364384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dbfa54df8f21"
down_revision = "df2e5a79269f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DOWN",
                "START",
                "UP",
                "STOP",
                "WARNING",
                "ERROR",
                "CRITICAL",
                "CLEAN",
                name="botstatus",
            ),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("message", sa.String(length=256), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot")),
    )
    op.create_table(
        "bot_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL", name="botloglevel"
            ),
            nullable=False,
        ),
        sa.Column("message", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bot.id"], name=op.f("fk_bot_logs_bot_id_bot")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_logs")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bot_logs")
    op.drop_table("bot")
    # ### end Alembic commands ###
