"""ticket order

Revision ID: f6be265d9f21
Revises: 623673a2c254
Create Date: 2023-08-11 15:42:09.350237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6be265d9f21'
down_revision = '623673a2c254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_date_id', sa.Integer(), nullable=False),
    sa.Column('ticket_time_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'DONE', 'CANCELED', name='orderstatus'), server_default='NEW', nullable=False),
    sa.ForeignKeyConstraint(['ticket_date_id'], ['tickets_date.id'], name=op.f('fk_tickets_order_ticket_date_id_tickets_date')),
    sa.ForeignKeyConstraint(['ticket_time_id'], ['tickets_time.id'], name=op.f('fk_tickets_order_ticket_time_id_tickets_time')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tickets_order_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets_order'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets_order')
    # ### end Alembic commands ###
