name: RELEASE

on:
  # release:
  #   types:
  #     - released
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]

env:
  DOCKER_LOGIN: simple2b

jobs:
  deploy:
    runs-on: Linux
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: update compose file
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          source: docker-compose.prod.yaml
          target: ~/paris
      - name: deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd ~/paris &&
            mv docker-compose.prod.yaml docker-compose.yaml &&
            docker-compose pull &&
            docker-compose down &&
            docker-compose up -d &&
            docker system prune -f
