name: RELEASE

on:
  release:
    types:
      - released

env:
  DOCKER_LOGIN: simple2b

jobs:
  deploy:
    runs-on: Linux
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd ~/kebab-estate
            docker-compose pull web &&
            docker-compose up -d web
