name: Testing

on: push

env:
  DEPLOY_HOST: ${{ secrets.PROD_HOST }}
  DEPLOY_USER_NAME: ${{ secrets.PROD_USERNAME }}
  DEPLOY_SSH_KEY: ${{ secrets.PROD_SSH_KEY }}

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.11]
        poetry-version: [1.5.1]
        os: [Linux]
    runs-on: ${{ matrix.os }}

    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER_NAME }}
          key: ${{ env.DEPLOY_SSH_KEY }}
          script: |
            ls -la
